name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        shell: pwsh  # Force PowerShell on Windows
        run: |
          pip install pyinstaller PyQt6
          if ($env:RUNNER_OS -eq "Windows") {
            pip install pywin32
          }

      - name: Build
        shell: pwsh
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            pyinstaller --onefile --windowed --icon src/icon.ico --add-data "src/calculatorui.ui;." --name Calculator src/calculator.py
          } else {
            pyinstaller --onefile --windowed --icon src/icon.png --add-data "src/calculatorui.ui:." --name Calculator src/calculator.py
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Calculator-${{ matrix.os }}
          path: dist/