name: Build
on: [push]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies (Windows)
        run: |
          pip install pyinstaller PyQt6 pywin32
      
      - name: Build Windows EXE
        run: |
          pyinstaller --onefile --windowed --icon src/icon.ico --add-data "src/calculatorui.ui;." --name Calculator src/calculator.py
      
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Calculator-Windows
          path: dist/Calculator.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          pip install pyinstaller PyQt6
      
      - name: Build Linux Binary
        run: |
          pyinstaller --onefile --windowed --icon src/icon.png --add-data "src/calculatorui.ui:." --name Calculator src/calculator.py
      
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Calculator-Linux
          path: dist/Calculator

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies (macOS)
        run: |
          pip install pyinstaller PyQt6
      
      - name: Build Mac Binary
        run: |
          pyinstaller --onefile --windowed --icon src/icon.png --add-data "src/calculatorui.ui:." --name Calculator src/calculator.py
      
      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Calculator-Mac
          path: dist/Calculator